[package]
name = "yyy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
yyy-web = { path = "../web" }
