[package]
name = "yyy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
env_logger.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
yyy-web = { path = "../web" }
